### ISSUE TITLE
Come up with a better name.

### ISSUE THREAD

**Issue by MMazzocchi** [MMazzocchi/space-dud#9]
"gamepad-server-plugin" straight up sucks. Either come up with something descriptive, like "gamepad-event-stream" or something cool, like "wormhole".

**Comment by joshuaunderwood7** [comment]
I think "space-dud" is a cool name. Also I think "quarrel" would be pretty rad.

**Comment by MMazzocchi** [comment]
"quarrel" is taken, so "space-dud" it is!
